version: "3"
services:
  windows:
    image: gustavogmoraes/windows
    container_name: windows
    environment:
      VERSION: "core11"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
